#---------------- Create FADN.code.key ------------------------------
N <- 148  
FADN.code.key <- data.frame(code=rep("",N),
                            description=rep("",N),
                            stringsAsFactors=F)


FADN.code.key[1,]   <- c("SYS02", "Farms represented")
FADN.code.key[2,]   <- c("SYS03", "Sample farms")
FADN.code.key[3,]   <- c("SE005", "Economic size")
FADN.code.key[4,]   <- c("SE010", "Total labour input")
FADN.code.key[5,]   <- c("SE011", "Labour input")
FADN.code.key[6,]   <- c("SE015", "Unpaid labour input")
FADN.code.key[7,]   <- c("SE020", "Paid labour input")
FADN.code.key[8,]   <- c("SE021", "Paid labour Input")
FADN.code.key[9,]   <- c("SE025", "Total Utilised Agricultural Area")
FADN.code.key[10,]  <- c("SE030", "Rented U.A.A.")
FADN.code.key[11,]  <- c("SE016", "Unpaid labour input")
FADN.code.key[12,]  <- c("SE035", "Cereals")
FADN.code.key[13,]  <- c("SE041", "Other field crops")
FADN.code.key[14,]  <- c("SE042", "Energy crops")
FADN.code.key[15,]  <- c("SE046", "Vegetables and flowers")
FADN.code.key[16,]  <- c("SE050", "Vineyards")
FADN.code.key[17,]  <- c("SE054", "Permanent crops")
FADN.code.key[18,]  <- c("SE060", "Olive groves")
FADN.code.key[19,]  <- c("SE055", "Orchards")
FADN.code.key[20,]  <- c("SE065", "Other permanent crops")
FADN.code.key[21,]  <- c("SE071", "Forage crops")
FADN.code.key[22,]  <- c("SE072", "Agricultural fallows")
FADN.code.key[23,]  <- c("SE073", "Set aside")
FADN.code.key[24,]  <- c("SE074", "Total agricultural area out of production")
FADN.code.key[25,]  <- c("SE075", "Woodland area")
FADN.code.key[26,]  <- c("SE080", "Total livestock units")
FADN.code.key[27,]  <- c("SE085", "Dairy cows")
FADN.code.key[28,]  <- c("SE090", "Other cattle")
FADN.code.key[29,]  <- c("SE095", "Sheep and goats")
FADN.code.key[30,]  <- c("SE100", "Pigs")
FADN.code.key[31,]  <- c("SE105", "Poultry")
FADN.code.key[32,]  <- c("SE110", "Yield of wheat")
FADN.code.key[33,]  <- c("SE115", "Yield of maize")
FADN.code.key[34,]  <- c("SE120", "Stocking density")
FADN.code.key[35,]  <- c("SE125", "Milk yield")
FADN.code.key[36,]  <- c("SE131", "Total output")
FADN.code.key[37,]  <- c("SE132", "Total output / Total input")
FADN.code.key[38,]  <- c("SE135", "Total output crops & crop production")
FADN.code.key[39,]  <- c("SE136", "Total crops output / ha")
FADN.code.key[40,]  <- c("SE140", "Cereals")
FADN.code.key[41,]  <- c("SE145", "Protein crops")
FADN.code.key[42,]  <- c("SE146", "Energy crops")
FADN.code.key[43,]  <- c("SE150", "Potatoes")
FADN.code.key[44,]  <- c("SE155", "Sugar beet")
FADN.code.key[45,]  <- c("SE160", "Oil-seed crops")
FADN.code.key[46,]  <- c("SE165", "Industrial crops")
FADN.code.key[47,]  <- c("SE170", "Vegetables & flowers")
FADN.code.key[48,]  <- c("SE175", "Fruit")
FADN.code.key[49,]  <- c("SE180", "Citrus fruit")
FADN.code.key[50,]  <- c("SE185", "Wine and grapes")
FADN.code.key[51,]  <- c("SE190", "Olives & olive oil")
FADN.code.key[52,]  <- c("SE195", "Forage crops")
FADN.code.key[53,]  <- c("SE200", "Other crop output")
FADN.code.key[54,]  <- c("SE206", "Total output livestock & livestock products")
FADN.code.key[55,]  <- c("SE207", "Total livestock output / LU")
FADN.code.key[56,]  <- c("SE211", "Change in value of livestock")
FADN.code.key[57,]  <- c("SE216", "Cows' milk & milk products")
FADN.code.key[58,]  <- c("SE220", "Beef and veal")
FADN.code.key[59,]  <- c("SE225", "Pigmeat")
FADN.code.key[60,]  <- c("SE230", "Sheep and goats")
FADN.code.key[61,]  <- c("SE235", "Poultrymeat")
FADN.code.key[62,]  <- c("SE240", "Eggs")
FADN.code.key[63,]  <- c("SE245", "Ewes' and goats' milk")
FADN.code.key[64,]  <- c("SE251", "Other livestock & products")
FADN.code.key[65,]  <- c("SE256", "Other output")
FADN.code.key[66,]  <- c("SE260", "Farmhouse consumption")
FADN.code.key[67,]  <- c("SE265", "Farm use")
FADN.code.key[68,]  <- c("SE270", "Total Inputs")
FADN.code.key[69,]  <- c("SE275", "Total intermediate consumption")
FADN.code.key[70,]  <- c("SE281", "Total specific costs")
FADN.code.key[71,]  <- c("SE284", "Specific crop costs / ha")
FADN.code.key[72,]  <- c("SE285", "Seeds and plants")
FADN.code.key[73,]  <- c("SE290", "Seeds and plants home-grown")
FADN.code.key[74,]  <- c("SE295", "Fertilisers")
FADN.code.key[75,]  <- c("SE300", "Crop protection")
FADN.code.key[76,]  <- c("SE305", "Other crop specific costs")
FADN.code.key[77,]  <- c("SE309", "Specific livestock output / LU")
FADN.code.key[78,]  <- c("SE310", "Feed for grazing livestock")
FADN.code.key[79,]  <- c("SE315", "Feed for grazing livestock home-grown")
FADN.code.key[80,]  <- c("SE320", "Feed for pigs & poultry")
FADN.code.key[81,]  <- c("SE325", "Feed for pigs&poultry home-grown")
FADN.code.key[82,]  <- c("SE330", "Other livestock specific costs")
FADN.code.key[83,]  <- c("SE331", "Forestry specific costs")
FADN.code.key[84,]  <- c("SE336", "Total farming overheads")
FADN.code.key[85,]  <- c("SE340", "Machinery & building current costs")
FADN.code.key[86,]  <- c("SE345", "Energy")
FADN.code.key[87,]  <- c("SE350", "Contract work")
FADN.code.key[88,]  <- c("SE356", "Other direct inputs")
FADN.code.key[89,]  <- c("SE360", "Depreciation")
FADN.code.key[90,]  <- c("SE365", "Total external factors")
FADN.code.key[91,]  <- c("SE370", "Wages paid")
FADN.code.key[92,]  <- c("SE375", "Rent paid")
FADN.code.key[93,]  <- c("SE380", "Interest paid")
FADN.code.key[94,]  <- c("SE390", "Taxes")
FADN.code.key[95,]  <- c("SE395", "VAT balance excluding on investments")
FADN.code.key[96,]  <- c("SE405", "Balance subsidies & taxes on investments")
FADN.code.key[97,]  <- c("SE406", "Subsidies on investments")
FADN.code.key[98,]  <- c("SE407", "Payments to dairy outgoers")
FADN.code.key[99,]  <- c("SE408", "VAT on investments")
FADN.code.key[100,] <- c("SE410", "Gross Farm Income")
FADN.code.key[101,] <- c("SE415", "Farm Net Value Added")
FADN.code.key[102,] <- c("SE420", "Farm Net Income")
FADN.code.key[103,] <- c("SE425", "Farm Net Value Added / AWU")
FADN.code.key[104,] <- c("SE430", "Farm Net Income / FWU")
FADN.code.key[105,] <- c("SE436", "Total assets")
FADN.code.key[106,] <- c("SE441", "Total fixed assets")
FADN.code.key[107,] <- c("SE446", "Land, permanent crops & quotas")
FADN.code.key[108,] <- c("SE450", "Buildings")
FADN.code.key[109,] <- c("SE455", "Machinery")
FADN.code.key[110,] <- c("SE460", "Breeding livestock")
FADN.code.key[111,] <- c("SE465", "Total current assets")
FADN.code.key[112,] <- c("SE470", "Non-breeding livestock")
FADN.code.key[113,] <- c("SE475", "Stock of agricultural products")
FADN.code.key[114,] <- c("SE480", "Other circulating capital")
FADN.code.key[115,] <- c("SE485", "Total liabilities")
FADN.code.key[116,] <- c("SE490", "Long & medium-term loans")
FADN.code.key[117,] <- c("SE495", "Short-term loans")
FADN.code.key[118,] <- c("SE501", "Net worth")
FADN.code.key[119,] <- c("SE506", "Change in net worth")
FADN.code.key[120,] <- c("SE510", "Average farm capital")
FADN.code.key[121,] <- c("SE516", "Gross Investment")
FADN.code.key[122,] <- c("SE521", "Net Investment")
FADN.code.key[123,] <- c("SE526", "Cash Flow (1)")
FADN.code.key[124,] <- c("SE530", "Cash Flow (2)")
FADN.code.key[125,] <- c("SE532", "Cash flow / farm total capital")
FADN.code.key[126,] <- c("SE600", "Balance current subsidies & taxes")
FADN.code.key[127,] <- c("SE605", "Total subsidies - excluding on investments")
FADN.code.key[128,] <- c("SE610", "Total subsidies on crops")
FADN.code.key[129,] <- c("SE611", "Compensatory payments/area payments")
FADN.code.key[130,] <- c("SE612", "Set aside premiums")
FADN.code.key[131,] <- c("SE613", "Other crops subsidies")
FADN.code.key[132,] <- c("SE615", "Total subsidies on livestock")
FADN.code.key[133,] <- c("SE616", "Subsidies dairying")
FADN.code.key[134,] <- c("SE617", "Subsidies other cattle")
FADN.code.key[135,] <- c("SE618", "Subsidies sheep & goats")
FADN.code.key[136,] <- c("SE619", "Other livestock subsidies")
FADN.code.key[137,] <- c("SE621", "Environmental subsidies")
FADN.code.key[138,] <- c("SE622", "LFA subsidies")
FADN.code.key[139,] <- c("SE624", "Total support for rural development")
FADN.code.key[140,] <- c("SE623", "Other rural development payments")
FADN.code.key[141,] <- c("SE699", "Other subsidies")
FADN.code.key[142,] <- c("SE625", "Subsidies on intermediate consumption")
FADN.code.key[143,] <- c("SE626", "Subsidies on external factors")
FADN.code.key[144,] <- c("SE630", "Decoupled payments")
FADN.code.key[145,] <- c("SE631", "Single Farm payment")
FADN.code.key[146,] <- c("SE632", "Single Area payment")
FADN.code.key[147,] <- c("SE640", "Additional aid")
FADN.code.key[148,] <- c("SE650", "Support_Art68")

rm(N)
FADN.code.key <- data.table(FADN.code.key, key=c("code", "description"))
View(FADN.code.key)
#---------------- Create FADN.code.key ------------------------------



#---------------- Define key function  ------------------------------

# Convenience function- takes code and returns description 
FADNlookup <- function(code.or.desc, reverse=F){
  
  if  (reverse==F){
  output <- FADN.code.key[code.or.desc][, description]
  output <- gsub("[[:punct:]]", "", output)
  output <- gsub(" ", ".", output)
  }
  
  if  (reverse==T){
  output <- FADN.code.key[code.or.desc][, code]
  }
  
  if  (reverse!=T && reverse!=F){
    stop("<reverse> is a logical argument.Please set it to T or F.")
  }  
  
  return(output)

}
#---------------- Define key function  ------------------------------

